twitch:
  token: "YOUR TOKEN"
  channels:
    - 120114410

players:
  - sintcraft

# PLACEHOLDERS
# %streamer%
# %username%
# %%
rewards:
  0:
    preset: "summon" # summon / place / give / drop / tp / command / skin / skin-random
    price:
      points: 400 # none or number
      bits: 12 # none or number
    settings:
      summon-radius: 3
      type: "ZOMBIE" #https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
      name: "%username%'s"
      equip-default: true
      health: 20
    notify:
      twitch-msg: ""
      minecraft-msg: "&b%usernames%'s &fspawn one zombie!"
      title: "" # "" don't send title
      subtitle: "" # "" don't send subtitle
      title-fadein: 20
      title-fadeout: 20
      actionbar: ""
      sound:
        sound: "ENTITY_PLAYER_LEVELUP" # "" or https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
        pitch: 1
        volume: 1