twitch:
  token: "YOUR TOKEN"
  channels:
    - 120114410

players:
  - sintcraft

# PLACEHOLDERS
# %streamer%
# %username%
# %type%
rewards:
  0:
    preset: "summon" # summon / give / drop / tp / place / command / skin / skin-random
    price:
      points: 40 # none or number
      bits: 12 # none or number
    settings:
      summon-radius: 3 # double, 0 spawn in player position
      amount: 2 # integer
      type: "ZOMBIE" # Types in https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
      name: "%username%'s" # Name of the mob
      equip-default: true # Modify vanilla enabled
      health: 20 # Integer minimum 0
      top-world: false # mob spawn in top of the world
    notify:
      twitch-msg: "" # "" don't send message in twitch
      minecraft-msg: "&b%username%'s &fspawn two zombies!" # "" don't send message in minecraft
      title: "&b%username%'s &fReward!" # "" don't send title
      subtitle: "&fSpawn a &2zombies" # "" don't send subtitle
      title-fadein: 20 # Integer in ticks
      title-fadeout: 20 # Integer in ticks
      actionbar: "&aReward type: &d%type%" # "" don't send actionbar
      sound:
        sound: "ENTITY_PLAYER_LEVELUP" # "" or https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
        pitch: 2
        volume: 0.3
  1:
    preset: "give" # summon / give / drop / tp / place / command / skin / skin-random
    price:
      points: 40 # none or number
      bits: 12 # none or number
    settings:
      slot: -1 # set -1 for random slot or integer number (0-45)
      amount: 2 # Integer minimum 1
      material: "POTATO" # Material list in https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
      name: "" # "" for item's default name
      lore: # "" for no lore
        - "%username%'s reward"
    notify:
      twitch-msg: "" # "" don't send message in twitch
      minecraft-msg: "&b%username%'s &fgive a potato!" # "" don't send message in minecraft
      title: "&b%username%'s &fReward!" # "" don't send title
      subtitle: "" # "" don't send subtitle
      title-fadein: 20 # Integer in ticks
      title-fadeout: 20 # Integer in ticks
      actionbar: "&aReward type: &d%type%" # "" don't send actionbar
      sound:
        sound: "ENTITY_EXPERIENCE_ORB_PICKUP" # "" or https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
        pitch: 1
        volume: 0.3
  2:
    preset: "drop" # summon / give / drop / tp / place / command / skin / skin-random
    price:
      points: 40 # none or number
      bits: 12 # none or number
    settings:
      mode: "drop" # drop / delete
      slot: "main-hand" # main-hand / second-hand / helmet / chestplate / leggings / boots / random
      amount: 2 # Set -1 for all items in this slot Integer minimum 1
    notify:
      twitch-msg: "" # "" don't send message in twitch
      minecraft-msg: "&b%username%'s &fdrop a item in main hand!" # "" don't send message in minecraft
      title: "&b%username%'s &fReward!" # "" don't send title
      subtitle: "" # "" don't send subtitle
      title-fadein: 20 # Integer in ticks
      title-fadeout: 20 # Integer in ticks
      actionbar: "" # "" don't send actionbar
      sound:
        sound: "ENTITY_EXPERIENCE_ORB_PICKUP" # "" or https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
        pitch: 1
        volume: 0.3
  3:
    preset: "tp" # summon / give / drop / tp / place / command / skin / skin-random
    price:
      points: 40 # none or number
      bits: 12 # none or number
    settings:
      mode: "random" # random / equals / random-center
      top-world: false # mob spawn in top of the world
      x: 10 # Double use in all modes
      y: 5 # Double use in all modes, set 0 for equals player height.
      z: 10 # Double use in all modes
    notify:
      twitch-msg: "" # "" don't send message in twitch
      minecraft-msg: "&b%username%'s &fteleport random!" # "" don't send message in minecraft
      title: "" # "" don't send title
      subtitle: "" # "" don't send subtitle
      title-fadein: 20 # Integer in ticks
      title-fadeout: 20 # Integer in ticks
      actionbar: "&aReward type: &d%type%" # "" don't send actionbar
      sound:
        sound: "ENTITY_WARDEN_EMERGE" # "" or https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
        pitch: 1
        volume: 0.3
  4:
    preset: "place" # summon / give / drop / tp / place / command / skin / skin-random
    price:
      points: 400 # none or number
      bits: 12 # none or number
    settings:
      position: "player" # player / world
      blocks:
        '0':
          material: "IRON_BARS" # Material list in https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
          cords: [1, 0, 1] # [x, y, z] | floor is y=-1
        '1':
          material: "IRON_BARS"
          cords: [1, 0, 1]
    notify:
      twitch-msg: "" # "" don't send message in twitch
      minecraft-msg: "&b%username%'s &fplace a cage!" # "" don't send message in minecraft
      title: "&b%username%'s &fowo!" # "" don't send title
      subtitle: "Hi!" # "" don't send subtitle
      title-fadein: 20 # Integer in ticks
      title-fadeout: 20 # Integer in ticks
      actionbar: "&aReward type: &d%type%" # "" don't send actionbar
      sound:
        sound: "ENTITY_EXPERIENCE_ORB_PICKUP" # "" or https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
        pitch: 1
        volume: 0.3
  5:
    preset: "command" # summon / give / drop / tp / place / command / skin / skin-random
    price:
      points: 0 # none or number
      bits: 12 # none or number
    settings:
      sender: "player" # player / console
      delay: 0 # delay between command
      commands:
        - "say hola"
    notify:
      twitch-msg: "" # "" don't send message in twitch
      minecraft-msg: "&b%username%'s &fchange!" # "" don't send message in minecraft
      title: "&b%username%'s &fowo!" # "" don't send title
      subtitle: "Hi!" # "" don't send subtitle
      title-fadein: 20 # Integer in ticks
      title-fadeout: 20 # Integer in ticks
      actionbar: "&aReward type: &d%type%" # "" don't send actionbar
      sound:
        sound: "ENTITY_EXPERIENCE_ORB_PICKUP" # "" or https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
        pitch: 1
        volume: 0.3